


CREATE VIEW Employee_Absense_View
as
SELECT 
PERSON_REF,
INT_EMP_ATT_POST_REF
,DATEFROMPARTS('20'+left(START_DATE,2),SUBSTRING(START_DATE,4,2),right(START_DATE,2)) Start_Date
,DATEADD(dd,CONVERT(INT,CASE WHEN [INT_EMP_ATT_TOT_DAYS_TAKEN]<=1 THEN 0 ELSE [INT_EMP_ATT_TOT_DAYS_TAKEN] END) ,DATEFROMPARTS('20'+left(START_DATE,2),SUBSTRING(START_DATE,4,2),right(START_DATE,2))) End_Date
,INT_EMP_ATT_ABS_TYPE
,INT_EMP_ATT_ABS_REASON
,INT_EMP_ATT_TOT_DAYS_TAKEN
FROM [dbo].[RAW_D6820M]