SELECT    r.EMPLOYEE_NUMBER , m. PERSON_REF,SURNAME,FIRST_FORNAME,ETHNIC_ORIGIN,sex gender,m.PERS_DISABILITY_ONE+m.PERS_DISABILITY_TWO ,r.START_DATE
,r.END_DATE


 FROM raw_d500m m

INNER JOIN raw_d550m r ON m.PERSON_REF=r.PERSON_REF