SELECT       
CASE 
   WHEN n.EMPLOYEE_CLEAN_JOB_TITLE IS NULL THEN  0
   WHEN  n.EMPLOYEE_CLEAN_JOB_TITLE <>WR_VAC_LONG_DESC THEN 1 ELSE 0 END [Change Of Post]
   ,n.EMPLOYEE_CLEAN_JOB_TITLE
 ,v.WR_VAC_LONG_DESC
,n.EMPLOYEE_START_DATE,n.EMPLOYEE_POST_START_DATE
, v.WR_VAC_START_DATE
, e.WR_APP_REF
WR_APP_TITLE, 
WR_APP_FIRST_NAME,
 WR_APP_LAST_NAME, 
 DATEDIFF( YEAR,WR_APP_DOB,GETDATE()) Age, 
WR_APP_EO_GENDER, 
WR_APP_EO_ETH_GROUP
, v.WR_VAC_REF
 ,v.WR_VAC_POST_DESC,
 
 
  v.WR_VAC_SETUP_DATE,
  v.WR_VAC_REQ_DATE,
  v.WR_VAC_CLOSED_DATE,
  v.WR_VAC_APP_CLOSE_DATE
  ,e.PERSON_REF
 
FROM          dbo.RAW_RL101M v  

INNER JOIN [dbo].[RAW_RL102M] r  ON v.WR_VAC_REF=r.WR_VAC_REF
INNER JOIN  Raw_Rl100m e ON r.wr_app_ref=e.WR_APP_REF

LEFT JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS n ON n.EMPLOYEE_PERSON_REFERENCE=e.PERSON_REF
WHERE v.WR_VAC_APP_CLOSE_DATE>GETDATE()