SELECT       
n.EMPLOYEE_CLEAN_JOB_TITLE
,n.EMPLOYEE_START_DATE,n.EMPLOYEE_POST_START_DATE
,

  v.WR_VAC_START_DATE
, e.WR_APP_REF

 WR_APP_TITLE, WR_APP_FIRST_NAME, WR_APP_LAST_NAME
	 , DATEDIFF( YEAR,WR_APP_DOB,GETDATE()) Age, 
WR_APP_EO_GENDER, 
WR_APP_EO_ETH_GROUP

, v.WR_VAC_REF
 
 ,
  v.WR_VAC_POST_DESC,
  v.WR_VAC_LONG_DESC,
 
  v.WR_VAC_SETUP_DATE,
  v.WR_VAC_REQ_DATE,
  v.WR_VAC_CLOSED_DATE,
  v.WR_VAC_APP_CLOSE_DATE
  ,e.PERSON_REF
 
FROM          dbo.RAW_RL101M v  

left JOIN [dbo].[RAW_RL102M] r  ON v.WR_VAC_REF=r.WR_VAC_REF
left JOIN  Raw_Rl100m e ON r.wr_app_ref=e.WR_APP_REF

LEFT JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS n ON n.EMPLOYEE_PERSON_REFERENCE=e.PERSON_REF


WHERE v.WR_VAC_APP_CLOSE_DATE>GETDATE()

SELECT * FROM dbo.RAW_RL101M v 


TRUNCATE TABLE Raw_Rl100m 
TRUNCATE TABLE Raw_Rl101m 
TRUNCATE TABLE Raw_Rl102m 



SELECT * FROM dbo.RL_Meta
WHERE TABLE_NAME LIKE 'RL%'
AND COLUMN_NAME LIKE '%person%'



----01004301

SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
WHERE EMPLOYEE_POST_REFERENCE=01004301



SELECT * FROM raw_d500m r

WHERE
r.PERSON_REF=