


SELECT--- vr.POST_REF,
vr.VACANCY_REF ,e.PERSON_REF---,vr.*

FROM  raw_D270M vr 
INNER JOIN dbo.RAW_RL101M r ON vr.VACANCY_REF=r.WR_VAC_REF
INNER JOIN dbo.raw_RL102M m ON m.WR_VAC_REF=r.WR_VAC_REF
INNER JOIN Raw_Rl100m e ON m.WR_APP_REF=e.WR_APP_REF
INNER JOIN  raw_d580m p ON p.PERSON_REF=e.PERSON_REF
AND p.REF<>vr.POST_REF
WHERE
 vr.CLOSED_DATE IS null
AND
( p.END_DATE IS NULL OR p.END_DATE>GETDATE())
AND e.PERSON_REF=01073745
GROUP BY -- vr.POST_REF,
vr.VACANCY_REF ,e.PERSON_REF