USE [H21_STAGING]
GO

/****** Object:  StoredProcedure [dbo].[PAYROLL_GL_JOURNAL]    Script Date: 27/04/2020 09:30:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/**
AUTHOR                                  DATE                                        DESC

PRAVEEN NAYAKWADI                        29/01/2020                                 Payroll Gl Journal  Intial Version

**/
CREATE PROCEDURE [dbo].[PAYROLL_GL_JOURNAL]
@RUN_NO VARCHAR(8),
@PAY_ST_ID VARCHAR(10)



AS

----PAYROLL_GL_JOURNAL 'ALL','ALL'
--SET @RUN_NO = '01006127'
--SET @PAY_ST_ID = 'MONTHLY28'

SELECT 
DISTINCT 
	CASE	WHEN T1.COST_PAY_OR_DEDN_FLAG = 'D' THEN T1.COST_AMOUNT * - 1
			ELSE T1.COST_AMOUNT
			END AS AMOUNT
	,T4.SORT_CODE
	,T3.LONG_DESC
	,T3.PAY_ELEMENT_ID
	,T2.INITIALS
	,T2.SURNAME
	,T1.COST_TYPE_ALPHA
	,T1.COST_TAX_YEAR_PER_SUPP_NO
	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 1, 2)	    GL1 	
	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 3, 4)	    GL2
	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 7, 3)      GL3
	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 10, 5)     GL4
	,T1.COST_PE_ID_CODE
	,T1.COST_PAY_TYPE 
	,T1.COST_PAY_OR_DEDN_FLAG
	,T1.COST_PAY_DATE
	,T1.COST_LEVEL1_PAY_STR_ID
	,T1.COST_AMOUNT 
	,T1.EMPLOYEE_NUMBER 
	,T1.LONG_COST_CENTRE_CODE 

FROM RAW_D415M T1
	INNER JOIN RAW_D500M T2 ON T1.PERSON_REF = T2.PERSON_REF
	INNER JOIN RAW_D755M T3 ON T1.COST_PE_ID = T3.PAY_ELEMENT_ID
	INNER JOIN RAW_D200M T5 ON T1.COST_POST_NUMBER = T5.NUMBER_R
	LEFT JOIN  RAW_D300M T4 ON T5.JOB_REF = T4.REF
WHERE   
(T1.COSTING_RUN_NUMBER		= @RUN_NO )
AND
(T1.COST_LEVEL1_PAY_STR_ID	= @PAY_ST_ID )
ORDER BY 
	COST_PAY_DATE ASC
	,GL2 ASC
	,EMPLOYEE_NUMBER ASC
	,GL3 ASC
	,GL4 ASC



GO




SELECT LONG_DESC,PAY_ELEMENT_ID FROM RAW_D755M 
GROUP BY LONG_DESC,PAY_ELEMENT_ID

SELECT *   FROM RAW_D200M 
WHERE SHORT_DESC='CM' AND OBS_DATE IS null
ORDER BY LONG_DESC

SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY
WHERE EMPLOYEE_CLEAN_JOB_TITLE LIKE '%court Manager%' AND EMPLOYEE_POST_END_DATE>GETDATE()

SELECT * FROM RAW_D300M T4
WHERE T4.SHORT_DESC='HCCM'