
  SELECT POST_NUMBER,COUNT(DISTINCT REF)---,CURRENT_GRADE 
FROM  dbo.RAW_D580v
WHERE CURRENT_GRADE<>'CWZERO' 
AND POST_END_DATE IS null
GROUP BY POST_NUMBER
HAVING COUNT(DISTINCT CURRENT_GRADE)>1




SELECT po.CURRENT_GRADE,po.POST_NUMBER,po.LOC_LONG_DESC FROM dbo.RAW_D580v po

WHERE po.POST_NUMBER IN ('0802','0921')
AND po.POST_END_DATE IS null


SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY
WHERE EMPLOYEE_LAST_NAME LIKE '%nayak%'

SELECT 
m.PERSON_REF,
v.FIRST_FORNAME,
v.SURNAME,
a.EMPLOYEE_CLEAN_JOB_TITLE,
v.CURRENT_GRADE,

COALESCE(MIN(CASE WHEN v.CURRENT_GRADE='CWZERO' THEN m.POINT_RATE   ELSE NULL END) ,MAX(m.POINT_VALUE) ) [PayRate/Salary]

FROM  raw_d554m m
INNER JOIN raw_d580v v ON v.PERSON_REF=m.PERSON_REF 
INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY a ON a.EMPLOYEE_PERSON_REFERENCE=m.PERSON_REF AND a.EMPLOYEE_POST_END_DATE>GETDATE()
--WHERE m.PERSON_REF='01072174'
AND m.END_DATE IS NULL AND v.POST_END_DATE  IS null
GROUP BY

m.PERSON_REF,
v.FIRST_FORNAME,
v.SURNAME,
a.EMPLOYEE_CLEAN_JOB_TITLE,v.CURRENT_GRADE



SELECT * FROM dbo.RAW_D554M
WHERE PERSON_REF IN ('01019442') AND END_DATE IS NULL




ACM,Dayrate/Sala