SELECT 
	---PERSON_REF,
	POST_REF---,P.CURRENT_GRADE,P.HR_FTE_HOURS
	,hr
	----,POINT_VALUE,POINT_RATE
	,COALESCE(CASE WHEN P.CURRENT_GRADE='CWZERO' THEN P.POINT_RATE ELSE NULL END 
	,[1000],[0900],[1077],[1311]) [sal/rate]

	FROM 
	(

		SELECT 
	DISTINCT R.PERSON_REF,
	R.POST_REF ,R.HR_FTE_HOURS
	,hr,R.CURRENT_GRADE,ID,R.AMOUNT,POINT_VALUE,POINT_RATE
	
	FROM 
	(
	SELECT M.PERSON_REF,M.POST_REF,V.CURRENT_GRADE,HR,HR.HR_FTE_HOURS,POINT_VALUE,POINT_RATE
	,
	 ROW_NUMBER() OVER (PARTITION BY M.PERSON_REF,M.POST_REF ORDER BY  EMP_PH_TAX_YEAR DESC, EMP_PH_TAX_PERIOD DESC)RN ,ID,M.AMOUNT
	
	FROM  raw_D559M  M
	INNER JOIN RAW_D580V V ON V.PERSON_REF=M.PERSON_REF AND V.REF=M.POST_REF AND V.POST_END_DATE IS NULL
	INNER JOIN raw_d591m HR ON HR.PERSON_REF=V.PERSON_REF AND HR.EMP_POST_REF=V.REF  AND hr.HR_END_DATE IS null
	LEFT JOIN raw_d554m  pr ON  pr.PERSON_REF=v.PERSON_REF  AND pr.POST_REF=v.REF AND pr.END_DATE IS null
	WHERE M.POST_REF>0 AND ID IN (1000,0900,1077,1311) 
	
) R


WHERE RN=1
) T

PIVOT (MAX(AMOUNT) FOR ID IN ([1000],[0900],[1077],[1311])) P

SELECT * FROM dbo.RAW_D755M
WHERE PAY_ELEMENT_ID IN (1000,0900,1077,1311,1002,1050,1002)---Basic Sal,tax gross,cleaning,care basic





SELECT 
	---PERSON_REF,
	POST_REF---,P.CURRENT_GRADE,P.HR_FTE_HOURS
	--,hr
	------,POINT_VALUE,POINT_RATE
	,COALESCE(CASE WHEN P.CURRENT_GRADE='CWZERO' THEN P.POINT_RATE ELSE NULL END 
	,[1000],[0900],[1077],[1311],[1002]) [sal/rate]

	FROM 
	(

		SELECT 
	DISTINCT R.PERSON_REF,
	R.POST_REF ,R.HR_FTE_HOURS
	,hr,R.CURRENT_GRADE,ID,R.AMOUNT,POINT_VALUE,POINT_RATE
	
	FROM 
	(
	SELECT M.PERSON_REF,M.POST_REF,V.CURRENT_GRADE,HR,HR.HR_FTE_HOURS,POINT_VALUE,POINT_RATE
	,
	 ROW_NUMBER() OVER (PARTITION BY M.PERSON_REF,M.POST_REF ORDER BY  EMP_PH_TAX_YEAR DESC, EMP_PH_TAX_PERIOD DESC)RN ,ID,M.AMOUNT
	
	FROM  raw_D559M  M
	INNER JOIN RAW_D580V V ON V.PERSON_REF=M.PERSON_REF AND V.REF=M.POST_REF AND (V.POST_END_DATE IS NULL OR v.POST_END_DATE>GETDATE())
	INNER JOIN raw_d591m HR ON HR.PERSON_REF=V.PERSON_REF AND HR.EMP_POST_REF=V.REF  AND hr.HR_END_DATE IS null
	LEFT JOIN raw_d554m  pr ON  pr.PERSON_REF=v.PERSON_REF  AND pr.POST_REF=v.REF AND pr.END_DATE IS null
	WHERE ---- M.POST_REF>0 AND 
	ID IN (1000,0900,1077,1311,1002,1333,1035,1002) 
	
) R


WHERE RN=1
) T

PIVOT (MAX(AMOUNT) FOR ID IN ([1000],[0900],[1077],[1311],[1002])) P