
IF OBJECT_ID('tempdb..#employee_manager_Hierar')           IS NOT NULL DROP TABLE #employee_manager_Hierar
IF OBJECT_ID('tempdb..#eer')                               IS NOT NULL DROP TABLE #eer    
IF OBJECT_ID('tempdb..#Employee_Parents')                  IS NOT NULL DROP TABLE #Employee_Parents
IF OBJECT_ID('tempdb..#EmployeeFinal')                     IS NOT NULL DROP TABLE #EmployeeFinal
IF OBJECT_ID('tempdb..#Employee_LineMgt_Hierarchy')        IS NOT NULL DROP TABLE #Employee_LineMgt_Hierarchy
--#Employee_LineMgt_Hierarchy

--CREATE  VIEW  [dbo].[Employee_Manager_Ref]
--AS


;WITH cte AS
(
 SELECT DISTINCT EMPLOYEE_DETAILS.PERSON_REF 
 ,pm.PERSON_REF Manager_Ref
 ---,pm.REF
 ,ROW_NUMBER()OVER (PARTITION  BY EMPLOYEE_DETAILS.PERSON_REF ORDER BY pm.START_DATE DESC,pm.main_flag ) MRno
 ,CONCAT(md.FIRST_FORNAME,' ',md.SURNAME) Manager_Name
 --,pm.REF Manager_Post_ref
 ,POST_TO_POST.POST_REF2
 FROM 
						DBO.RAW_D500M   EMPLOYEE_DETAILS
  INNER JOIN			DBO.RAW_D580M   EMPLOYEE_POST                   ON (EMPLOYEE_POST.PERSON_REF = EMPLOYEE_DETAILS.PERSON_REF ---AND EMPLOYEE_POST.MAIN_FLAG = 'Y' 
  AND EMPLOYEE_POST.END_DATE IS NULL ) 
  INNER JOIN			DBO.RAW_D228M   POST_TO_POST                    ON (POST_TO_POST.POST_REF1 = EMPLOYEE_POST.REF AND POST_TO_POST.POST_RELATIONSHIP = 'R' 
  AND POST_TO_POST.HIERARCHY_EFF_COMPDATE = (SELECT MIN (D116M.EFF_COMPDATE)  FROM DBO.RAW_D116M D116M WHERE D116M.ID = POST_TO_POST.HIERARCHY_ID 
   AND D116M.EFF_DATE <= DATEADD(DD,0,DATEDIFF(DD,0,GETDATE()))))
 
 LEFT JOIN raw_d580m pm ON pm.REF=POST_TO_POST.POST_REF2 AND (pm.END_DATE IS NULL OR pm.END_DATE>GETDATE()) AND pm.MAIN_FLAG='Y'
 LEFT JOIN raw_d500m Md ON md.PERSON_REF=pm.PERSON_REF
  
  WHERE (EMPLOYEE_POST.END_DATE IS NULL OR EMPLOYEE_POST.END_DATE>GETDATE())
   AND EMPLOYEE_POST.MAIN_FLAG='Y'
  ---- AND EMPLOYEE_DETAILS.PERSON_REF=01046631
)




SELECT cte.PERSON_REF,
       cte.Manager_Ref,cte.Manager_Name
	INTO #employee_manager_Hierar 
FROM cte 
WHERE mrno=1

--SELECT * INTO #employee_manager_Hierar  FROM  employee_manager_ref  
--SELECT * FROM dbo.Employee_Manager_Ref
--WHERE PERSON_REF=00007077


SELECT  DISTINCT    r.MANAGER_PERSON_REFERENCE PERSON_REFERENCE,a.LOCATION_DESCRIPTION,a.ADDRESS_LINE_ONE,a.ADDRESS_LINE_TWO,a.ADDRESS_LINE_THREE,a.ADDRESS_LINE_FOUR into #EmployeeFinal 
FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY r
INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY a ON a.EMPLOYEE_PERSON_REFERENCE=r.MANAGER_PERSON_REFERENCE
                                                 AND a.EMPLOYEE_POST_REFERENCE=r.MANAGER_POST_REFERENCE
WHERE  a.EMPLOYEE_POST_END_DATE>GETDATE() AND r.EMPLOYEE_POST_END_DATE>GETDATE()




INSERT INTO #EmployeeFinal 
SELECT  DISTINCT   EMPLOYEE_PERSON_REFERENCE PERSON_REFERENCE,a.LOCATION_DESCRIPTION,a.ADDRESS_LINE_ONE,a.ADDRESS_LINE_TWO,a.ADDRESS_LINE_THREE,a.ADDRESS_LINE_FOUR 
 FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY a
WHERE EMPLOYEE_CLEAN_JOB_TITLE LIKE '%Care Administrator%'
AND EMPLOYEE_POST_END_DATE>GETDATE() 




--SELECT * FROM #EmployeeFinal





-----NULL	ADAM	CULYER	Senior Building Surveyor - South	 	NULL	No


SELECT 
       r.[Email Address],
       r.[First Name],
       r.Surname,
       r.[Job Title],
       r.Telephone,
       r.Mobile,
      MAX( r.Active) Active --,
       --r.Latest_emp_jobtitle,
       --r.Latest_emp_jobtitle 
	   
	   
	   FROM (
SELECT 
e.PERSON_REF,
EMPLOYEE_EMAIL_ADDRESS [Email Address]
,EMPLOYEE_FIRST_NAME  [First Name]
,EMPLOYEE_LAST_NAME  [Surname]
,EMPLOYEE_CLEAN_JOB_TITLE [Job Title]
,e.WORK_TEL_NO [Telephone]
,EMPLOYEE_MOBILE_TELEPHONE_NUMBER [Mobile] ,
CASE WHEN EMPLOYEE_END_DATE>GETDATE() THEN 'Yes' ELSE 'No' END [Active]
,ROW_NUMBER() OVER (PARTITION BY e.PERSON_REF ORDER BY r.EMPLOYEE_POST_END_DATE desc  ) Latest_emp_jobtitle
---,ROW_NUMBER() OVER (PARTITION BY e.FIRST_FORNAME,r.MANAGER_LAST_NAME ORDER BY r.EMPLOYEE_END_DATE DESC) Latest_emp_jobtitle
-----,USER_GROUP
----,structure
FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY r
INNER JOIN raw_d500m e ON e.PERSON_REF=r.EMPLOYEE_PERSON_REFERENCE
INNER JOIN #EmployeeFinal ef ON ef.PERSON_REFERENCE=e.PERSON_REF

GROUP BY e.PERSON_REF,EMPLOYEE_EMAIL_ADDRESS,EMPLOYEE_FIRST_NAME,EMPLOYEE_LAST_NAME,EMPLOYEE_CLEAN_JOB_TITLE,e.WORK_TEL_NO ,EMPLOYEE_MOBILE_TELEPHONE_NUMBER,r.EMPLOYEE_POST_END_DATE,r.EMPLOYEE_END_DATE
) r


WHERE r.Latest_emp_jobtitle=1
AND ( r.Telephone IS NOT NULL OR LEN(LTRIM(RTRIM(r.Telephone)))>1)

GROUP BY r.[Email Address],
       r.[First Name],
       r.Surname,
       r.[Job Title],
       r.Telephone,
       r.Mobile
ORDER BY r.[First Name]


--SELECT  * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY

--WHERE EMPLOYEE_PERSON_REFERENCE IN (01062144,01072207)

----Cath.Gamble@housing21.org.uk	CATH	GAMBLE	Cleaner	 	NULL	Yes



--SELECT *  FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY r
--WHERE EMPLOYEE_LAST_NAME LIKE '%gamble%'  AND EMPLOYEE_FIRST_NAME LIKE '%cath%'
----AND EMPLOYEE_POST_END_DATE>GETDATE()