
SELECT 
EMPLOYEE_EMAIL_ADDRESS [Email Address]
,EMPLOYEE_FIRST_NAME  [First Name]
,EMPLOYEE_LAST_NAME  [Surname]
,EMPLOYEE_CLEAN_JOB_TITLE [Job Title]
,EMPLOYEE_TELEPHONE_NUMBER [Telephone Extension]
,EMPLOYEE_MOBILE_TELEPHONE_NUMBER [Mobile] ,
CASE WHEN EMPLOYEE_END_DATE>GETDATE() THEN 'Yes' ELSE 'No' END [Active]
-----,USER_GROUP
----,structure
FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY