
SELECT DISTINCT  y.D4 ,p.DEPARTMENT department,p.EMPLOYEE_ClEAN_JOB_TITLE job_title---,v.POST_NUMBER post_number
,p.EMPLOYEE_POST_REFERENCE post_ref, CASE WHEN t.CURRENT_GRADE='CWZERO'    THEN  p.EMPLOYEE_POST_CONTRACTED_HOURS ELSE COALESCE(r.FULL_AMOUNT,UNADJ_AMOUNT)  end [salary] 
---,p.EMPLOYEE_PERSON_REFERENCE
,p.EMPLOYEE_JOB_TYPE,p.PAYROLL_FREQUENCY

FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS p
LEFT JOIN (  select PERSON_REF,POST_REF,FULL_AMOUNT,UNADJ_AMOUNT FROM raw_D559M 
 WHERE  id=1000 AND EMP_PH_TAX_PERIOD=03 AND EMP_PH_TAX_YEAR=2022
) r ON r.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE
    AND r.POST_REF=p.EMPLOYEE_POST_REFERENCE 
	
INNER JOIN 
(	
SELECT  p.D4 ,ep.PERSON_REF,ep.EMP_POST_REF   FROM raw_d455m ep INNER JOIN dbo.RL_PERS_HIERARCHY p
ON ep.PERS_STR_REF_LINK=p.CHILD_ID

WHERE ep.EMP_POST_END_DATE IS NULL 
) y ON y.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE AND y.EMP_POST_REF=p.EMPLOYEE_POST_REFERENCE

left JOIN 
(
SELECT GRADE_LONG_DESC,CURRENT_GRADE,ref,PERSON_REF FROM dbo.RAW_D580v
WHERE POST_END_DATE IS null
) t ON t.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE AND t.REF=p.EMPLOYEE_POST_REFERENCE

WHERE EMPLOYEE_POST_END_DATE>GETDATE()


----AND p.EMPLOYEE_POST_CONTRACTED_HOURS>0

--AND r.PERSON_REF IS NULL

--select MAX(EMP_PH_TAX_PERIOD) r FROM raw_D559M 
-- WHERE   EMP_PH_TAX_YEAR=2022


--SELECT * FROM dbo.ETL_LOAD_TASK



select PERSON_REF,POST_REF,FULL_AMOUNT,UNADJ_AMOUNT FROM raw_D559M 
 WHERE  id=1000 AND EMP_PH_TAX_PERIOD=03 AND 
 
 EMP_PH_TAX_YEAR=2022
 AND PERSON_REF=01072174



 SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY
 WHERE EMPLOYEE_LAST_NAME LIKE '%nayak%'