
SELECT DISTINCT  y.D4 ,p.DEPARTMENT department,p.EMPLOYEE_ClEAN_JOB_TITLE job_title---,v.POST_NUMBER post_number
,p.EMPLOYEE_POST_REFERENCE post_ref, CASE WHEN t.CURRENT_GRADE='CWZERO'    THEN  p.EMPLOYEE_POST_CONTRACTED_HOURS ELSE COALESCE(r.FULL_AMOUNT,UNADJ_AMOUNT)  end [salary] 
---,p.EMPLOYEE_PERSON_REFERENCE
,p.EMPLOYEE_JOB_TYPE,p.PAYROLL_FREQUENCY

FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS p
LEFT JOIN (  select PERSON_REF,POST_REF,FULL_AMOUNT,UNADJ_AMOUNT FROM raw_D559M 
 WHERE  id=1000 AND EMP_PH_TAX_PERIOD=03 AND EMP_PH_TAX_YEAR=2022
) r ON r.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE
    AND r.POST_REF=p.EMPLOYEE_POST_REFERENCE 
	
INNER JOIN 
(	
SELECT  p.D4 ,ep.PERSON_REF,ep.EMP_POST_REF   FROM raw_d455m ep INNER JOIN dbo.RL_PERS_HIERARCHY p
ON ep.PERS_STR_REF_LINK=p.CHILD_ID

WHERE ep.EMP_POST_END_DATE IS NULL 
) y ON y.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE AND y.EMP_POST_REF=p.EMPLOYEE_POST_REFERENCE

left JOIN 
(
SELECT GRADE_LONG_DESC,CURRENT_GRADE,ref,PERSON_REF FROM dbo.RAW_D580v
WHERE POST_END_DATE IS null
) t ON t.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE AND t.REF=p.EMPLOYEE_POST_REFERENCE

WHERE EMPLOYEE_POST_END_DATE>GETDATE()


----AND p.EMPLOYEE_POST_CONTRACTED_HOURS>0

--AND r.PERSON_REF IS NULL

--select MAX(EMP_PH_TAX_PERIOD) r FROM raw_D559M 
-- WHERE   EMP_PH_TAX_YEAR=2022


--SELECT * FROM dbo.ETL_LOAD_TASK



select PERSON_REF,POST_REF,FULL_AMOUNT,UNADJ_AMOUNT FROM raw_D559M 
 WHERE  id=1000 AND EMP_PH_TAX_PERIOD=03 AND 
 
 EMP_PH_TAX_YEAR=2022
 AND PERSON_REF=01072174



 SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY
 WHERE EMPLOYEE_LAST_NAME LIKE '%nayak%'




 SELECT GRADE_LONG_DESC,CURRENT_GRADE,ref,PERSON_REF FROM dbo.RAW_D580v
WHERE POST_END_DATE IS NULL


----CWGTD
----CWzero



SELECT *  FROM dbo.RAW_D580v

select PERSON_REF,POST_REF,FULL_AMOUNT,UNADJ_AMOUNT FROM raw_D559M 
   WHERE  id=1000 AND EMP_PH_TAX_PERIOD=03 AND EMP_PH_TAX_YEAR=2022




   SELECT * FROM   dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY
   WHERE EMPLOYEE_LAST_NAME LIKE '%nayakwadi%'


   SELECT 
   FULL_AMOUNT,UNADJ_AMOUNT
   
   
   
    FROM 
 raw_D559M 
    WHERE  
	--id=1000  AND EMP_PH_TAX_YEAR=2022
	--AND 
	PERSON_REF=01072174
	ORDER BY EMP_PH_TAX_YEAR DESC
    

	SELECT * FROM dbo.RAW_D580v

	WHERE CURRENT_GRADE IN ('CWGTD','CWzero')
	AND POST_END_DATE IS NULL
    
	
	
	
	SELECT r.PERSON_REF,m.FIRST_FORNAME,m.SURNAME,POST_REF,LOC_LONG_DESC,CONTROL_GROUP_DESC AS Payfreq ,FULL_AMOUNT


	FROM
    (

	SELECT DISTINCT y.PERSON_REF,y.POST_REF,LOC_LONG_DESC,CONTROL_GROUP_DESC
	
	 , FULL_AMOUNT  ---,MAX(UNADJ_AMOUNT)
	--,MAX(y.EMP_PH_TAX_YEAR) yr
	,EMP_PH_TAX_YEAR
	,y.EMP_PH_TAX_PERIOD  payperiod
	
	,ROW_NUMBER() OVER (PARTITION BY y.POST_REF,y.PERSON_REF ORDER BY y.EMP_PH_TAX_YEAR desc, y.EMP_PH_TAX_PERIOD desc) rk
	FROM dbo.RAW_D580v p INNER JOIN  raw_D559M y ON p.PERSON_REF=y.PERSON_REF AND p.REF=y.POST_REF ---AND y.END_DATE IS null
	WHERE POST_LONG_DESC LIKE '%Care Administrator%'
	---AND y.POST_REF=01009262
	----AND y.EMP_PH_TAX_YEAR=2022
	AND POST_END_DATE IS NULL
	---AND id=1000
	GROUP BY y.PERSON_REF,y.POST_REF,p.LOC_LONG_DESC,p.CONTROL_GROUP_DESC,y.EMP_PH_TAX_PERIOD,y.FULL_AMOUNT,EMP_PH_TAX_YEAR

	) r
	INNER JOIN raw_d500m m ON m.PERSON_REF=r.PERSON_REF
	WHERE r.rk=1
	------01058469



	SELECT * FROM  dbo.RAW_D559M y
	WHERE y.POST_REF=01009262
	AND EMP_PH_TAX_YEAR=2022
ORDER BY EMP_PH_TAX_PERIOD


---acm
SELECT COUNT(DISTINCT PERSON_REF)  [No of Acm] FROM dbo.RAW_D580v
WHERE POST_END_DATE IS NULL AND POST_LONG_DESC LIKE '%Assistant Care Manager%'



	SELECT COUNT(DISTINCT PERSON_REF)
	FROM dbo.RAW_D580v
	WHERE POST_END_DATE IS NULL
AND POST_LONG_DESC='Care Worker'
	GROUP BY CURRENT_GRADE,POST_LONG_DESC,PERSON_REF



		SELECT * FROM  raw_d591M
		WHERE PERSON_REF='01072174'
		

			SELECT d. LONG_DESC ,p.PERSON_REF,p.AMOUNT,p.FULL_AMOUNT,p.UNADJ_AMOUNT FROM  raw_d557M   p
			INNER JOIN raw_d755m d ON p.ID=d.PAY_ELEMENT_ID
		     WHERE PERSON_REF='01072174'





			 SELECT 
	* FROM
    (

		SELECT  DISTINCT p.POST_REF,p.PERSON_REF,p.AMOUNT     ----,p.FULL_AMOUNT,p.UNADJ_AMOUNT ,h.HR,h.HR_FTE_HOURS 
		FROM  raw_d557M p
		---INNER JOIN raw_d591m h ON p.PERSON_REF=h.PERSON_REF
		       WHERE  p.POST_REF<>0
	AND  p.PERSON_REF='01072174'
		) r

		SELECT * FROM  raw_d557M p 




		SELECT EMPLOYEE_PERSON_REFERENCE , PAYROLL_FREQUENCY  FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
		WHERE EMPLOYEE_POST_END_DATE>GETDATE()
		GROUP BY EMPLOYEE_PERSON_REFERENCE,PAYROLL_FREQUENCY
		HAVING COUNT(DISTINCT EMPLOYEE_POST_NUMBER)>1


		SELECT * FROM dbo.RAW_D580v
		WHERE PERSON_REF='01066960'
		AND POST_END_DATE>GETDATE()


		SELECT * FROM dbo.ETL_LOAD_TASK



		
			 SELECT r.PERSON_REF
	 FROM
    (

		SELECT DISTINCT d.LONG_DESC   ----,p.FULL_AMOUNT,p.UNADJ_AMOUNT ,h.HR,h.HR_FTE_HOURS 
		FROM  raw_d557M p
		INNER JOIN raw_d755m d ON p.id=d.PAY_ELEMENT_ID
		---INNER JOIN raw_d591m h ON p.PERSON_REF=h.PERSON_REF
		       WHERE  p.POST_REF=0
		--WHERE p.PERSON_REF='01072174'
		) r



		DECLARE @cnt int
		DECLARE @ct VARCHAR(3000)=''
		DECLARE @query VARCHAR(5000)
		
		
--			SELECT  @cnt=COUNT(DISTINCT d.LONG_DESC ) ----,p.FULL_AMOUNT,p.UNADJ_AMOUNT ,h.HR,h.HR_FTE_HOURS 
--		FROM  raw_d557M p
--		INNER JOIN raw_d755m d ON p.id=d.PAY_ELEMENT_ID
--		---INNER JOIN raw_d591m h ON p.PERSON_REF=h.PERSON_REF
--		       WHERE  p.POST_REF=0
--WHILE @cnt>0

   
   --SELECT
   --long_desc ,ROW_NUMBER()OVER(ORDER BY long_desc)ln FROM 
   --(
 SELECT @ct=@ct+QUOTENAME(long_desc)+','  FROM (SELECT DISTINCT   d.LONG_DESC


   
		FROM  raw_d557M p
		INNER JOIN raw_d755m d ON p.id=d.PAY_ELEMENT_ID
		---INNER JOIN raw_d591m h ON p.PERSON_REF=h.PERSON_REF
		       WHERE  p.POST_REF=0)p

			 

	SELECT @query='SELECT 	p.PERSON_REF,'+@ct+'


		FROM 
		(
			 SELECT p.PERSON_REF,p.AMOUNT ,  d.LONG_DESC
FROM  raw_d557M p
		INNER JOIN raw_d755m d ON p.id=d.PAY_ELEMENT_ID
		---INNER JOIN raw_d591m h ON p.PERSON_REF=h.PERSON_REF
		       WHERE  p.POST_REF=0

			   ) r
			   
			   

			   pivot (Max(Amount) for  long_desc in ('+@ct+')) pv
			   
			   '
			
		SELECT @query

sELECT p.PERSON_REF,p.POST_REF,p.ID,p.AMOUNT,p.FULL_AMOUNT,p.UNADJ_AMOUNT,p.UNITS,p.RATE,d.LONG_DESC,p.FULL_UNITS
		FROM  raw_d557M p
		INNER JOIN raw_d755m d ON p.id=d.PAY_ELEMENT_ID
		---INNER JOIN raw_d591m h ON p.PERSON_REF=h.PERSON_REF
		       WHERE  p.POST_REF=0 ----AND p.PERSON_REF=01009867
			   AND p.UNITS>0

			   ORDER BY p.PERSON_REF



			   SELECT   
			 FROM dbo.RAW_D580v
			   WHERE POST_END_DATE IS NULL
               AND PERSON_REF=01085400
			   ORDER BY CURRENT_GRADE,PERSON_REF
			   ----CWSTDZ



			   SELECT EMPLOYEE_PERSON_REFERENCE,PAYROLL_FREQUENCY,EMPLOYEE_CLEAN_JOB_TITLE FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
			   WHERE EMPLOYEE_POST_END_DATE>GETDATE()
			   AND EMPLOYEE_CLEAN_JOB_TITLE LIKE '%care%'



			   SELECT * FROM dbo.RAW_D591M p
			   WHERE p.PERSON_REF='01085400'
		  
		  
		  
		  SELECT  pp.LONG_DESC,p.*    ----,p.FULL_AMOUNT,p.UNADJ_AMOUNT ,h.HR,h.HR_FTE_HOURS 
		FROM  raw_d557M p
		INNER JOIN raw_d755m pp ON pp.PAY_ELEMENT_ID=p.ID
		       WHERE  
			   ---p.POST_REF<>0
			   --AND p.UNITS>0
	---AND 
	 p.PERSON_REF='01085400'  
	---Care Basic Pay    


	SELECT *  FROM  raw_D554M
	WHERE PERSON_REF='01085400'



	---10.87
	SELECT * FROM raw_D591m


	SELECT 
	DISTINCT v.PERSON_REF,u.POST_REF
	
	---LOC_LONG_DESC,JOB_LONG_DESC,JOB_NUMBER ,  POST_NUMBER ,FIRST_FORNAME,SURNAME,CURRENT_GRADE,PAY_GROUP_DESC,pr.POINT_RATE,pr.POINT_VALUE,r.EMPLOYEE_CLEAN_JOB_TITLE,u.AMOUNT ,hr.HR
	FROM dbo.RAW_D580v v
	INNER JOIN raw_d554m pr ON pr.PERSON_REF=v.PERSON_REF AND v.REF=pr.POST_REF AND (pr.END_DATE IS NULL OR pr.END_DATE>GETDATE())
    INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY r ON r.EMPLOYEE_PERSON_REFERENCE=pr.PERSON_REF AND r.EMPLOYEE_POST_REFERENCE=v.REF AND (r.EMPLOYEE_POST_END_DATE>GETDATE())
INNER  JOIN raw_d557m u ON u.PERSON_REF=v.PERSON_REF  AND u.ID=0900

INNER JOIN raw_d591m hr ON hr.PERSON_REF=v.PERSON_REF AND hr.EMP_POST_REF=v.REF AND hr.HR_END_DATE IS NULL AND hr.hr>0
	WHERE (POST_END_DATE IS NULL OR v.POST_END_DATE>GETDATE())
    ORDER BY LOC_LONG_DESC,v.POST_NUMBER

	-----pointrate

	SELECT DISTINCT p.PERSON_REF FROM 
		  raw_d557M p
		OUTER APPLY
        (SELECT  person_ref FROM raw_d557m m WHERE m.id IN (0900,1077)   AND m.PERSON_REF=p.PERSON_REF AND p.POST_REF=m.POST_REF  AND m.id=p.ID)r 
		WHERE r.PERSON_REF IS NULL
        

	SELECT r.LONG_DESC ,p.* FROM   raw_d557M p
	INNER JOIN dbo.RAW_D755M r ON p.ID=r.PAY_ELEMENT_ID
		WHERE p.PERSON_REF=00006884


		
	SELECT DISTINCT  p.PERSON_REF FROM   raw_d557M p
		WHERE id<>1000
		EXCEPT 
	SELECT DISTINCT  p.PERSON_REF FROM   raw_d557M p
		WHERE id=1000



		SELECT PERSON_REF,EMP_POST_REF  ref FROM raw_d591m
		WHERE HR_END_DATE  IS NULL
		AND hr>0
     
except

			SELECT 
	DISTINCT v.PERSON_REF,v.ref 
	
	---LOC_LONG_DESC,JOB_LONG_DESC,JOB_NUMBER ,  POST_NUMBER ,FIRST_FORNAME,SURNAME,CURRENT_GRADE,PAY_GROUP_DESC,pr.POINT_RATE,pr.POINT_VALUE,r.EMPLOYEE_CLEAN_JOB_TITLE,u.AMOUNT ,hr.HR,u.POST_REF,id
	FROM dbo.RAW_D580v v
	INNER JOIN raw_d554m pr ON pr.PERSON_REF=v.PERSON_REF AND v.REF=pr.POST_REF AND (pr.END_DATE IS NULL OR pr.END_DATE>GETDATE())
    INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY r ON r.EMPLOYEE_PERSON_REFERENCE=pr.PERSON_REF AND r.EMPLOYEE_POST_REFERENCE=v.REF AND (r.EMPLOYEE_POST_END_DATE>GETDATE())
INNER  JOIN raw_d557m u ON u.PERSON_REF=v.PERSON_REF  AND u.ID IN (0900,1077)

INNER JOIN raw_d591m hr ON hr.PERSON_REF=v.PERSON_REF AND hr.EMP_POST_REF=v.REF AND hr.HR_END_DATE IS NULL ---AND hr.hr>0
	WHERE (POST_END_DATE IS NULL OR v.POST_END_DATE>GETDATE())



	----00000397	00000995

	SELECT * FROM raw_d557m 

	WHERE PERSON_REF=00000397




	AND v.PERSON_REF=1002244
	---00000397 00000995
	SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
	WHERE EMPLOYEE_PERSON_REFERENCE=1002244 AND EMPLOYEE_POST_REFERENCE=01009883
	AND EMPLOYEE_POST_END_DATE>GETDATE() 
	SELECT * FROM dbo.RAW_D591M 
	WHERE PERSON_REF=1002244 AND EMP_POST_REF=1009883


	SELECT  i.LONG_DESC,r.* FROM dbo.RAW_D557M r INNER JOIN raw_d755m i ON i.PAY_ELEMENT_ID=r.ID
	WHERE  PERSON_REF=1002244 AND POST_REF>0


	SELECT * FROM raw_d755m WHERE PAY_ELEMENT_ID=1077


	SELECT * FROM dbo.RAW_D557M
	WHERE PERSON_REF=01066242


	SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
	WHERE EMPLOYEE_POST_END_DATE>GETDATE() AND EMPLOYEE_POST_CONTRACTED_HOURS>0




	SELECT m.PERSON_REF,EMP_POST_REF FROM raw_d591m m
	INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS ap ON ap.EMPLOYEE_PERSON_REFERENCE=m.PERSON_REF AND ap.EMPLOYEE_POST_REFERENCE=m.EMP_POST_REF WHERE HR_END_DATE IS NULL AND HR>0 AND EMP_POST_REF>0 AND ap.EMPLOYEE_POST_END_DATE>GETDATE()
	except


		SELECT 
	DISTINCT v.PERSON_REF,v.ref 
	
	LOC_LONG_DESC,JOB_LONG_DESC,JOB_NUMBER ,  POST_NUMBER ,FIRST_FORNAME,SURNAME,CURRENT_GRADE,PAY_GROUP_DESC,pr.POINT_RATE,pr.POINT_VALUE
	,r.EMPLOYEE_CLEAN_JOB_TITLE
    ,pr.POINT_RATE*hr [Sala]
	,hr
	,u.AMOUNT
	--,e.LONG_DESC
	--,v.REF
	FROM dbo.RAW_D580v v
	left JOIN raw_d554m pr ON pr.PERSON_REF=v.PERSON_REF AND v.REF=pr.POST_REF AND (pr.END_DATE IS NULL OR pr.END_DATE>GETDATE())
    INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS r ON r.EMPLOYEE_PERSON_REFERENCE=pr.PERSON_REF AND r.EMPLOYEE_POST_REFERENCE=v.REF AND (r.EMPLOYEE_POST_END_DATE>GETDATE())
INNER  JOIN raw_d557m u ON u.PERSON_REF=v.PERSON_REF  AND u.ID IN (1311,1077,0800) ---AND u.POST_REF>0

   left JOIN raw_d591m hr ON hr.PERSON_REF=v.PERSON_REF AND hr.EMP_POST_REF=v.REF AND hr.HR_END_DATE IS NULL AND hr.hr>0
	INNER JOIN dbo.RAW_D755M e ON e.PAY_ELEMENT_ID=u.ID
	WHERE (POST_END_DATE IS NULL OR v.POST_END_DATE>GETDATE())
	AND  v.PERSON_REF=01042816

	---01042816	01008455

	SELECT * FROM dbo.RAW_D557M
	WHERE PERSON_REF=01031427
		SELECT * FROM dbo.RAW_D559M
	WHERE PERSON_REF=01031427

	--- D559M 

	SELECT  EMPLOYEE_PERSON_REFERENCE  FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
	WHERE EMPLOYEE_POST_END_DATE>GETDATE()
	GROUP BY EMPLOYEE_PERSON_REFERENCE
	HAVING COUNT(*)>1


	SELECT t.LONG_DESC,* FROM dbo.RAW_D557M o INNER JOIN dbo.RAW_D755M t ON o.id=t.PAY_ELEMENT_ID
	WHERE PERSON_REF=01091787 AND (POST_REF>0 OR id=0900 OR id=1000)
	
	SELECT * FROM dbo.RAW_D554M
	WHERE PERSON_REF='01073854' AND END_DATE IS NULL
    
	SELECT PERSON_REF,EMP_POST_REF FROM raw_d591m WHERE HR_END_DATE IS NULL AND HR>0
	GROUP BY  PERSON_REF,EMP_POST_REF 
    
	----3948.33
	-----1311,1077
	---3448

	SELECT 
	DISTINCT R.PERSON_REF,R.POST_REF ,ID,R.AMOUNT
	
	FROM 
	(
	SELECT M.PERSON_REF,M.POST_REF,ROW_NUMBER() OVER (PARTITION BY M.PERSON_REF,M.POST_REF ORDER BY  EMP_PH_TAX_YEAR DESC, EMP_PH_TAX_PERIOD DESC)RN ,ID,M.AMOUNT
	
	FROM  raw_D559M  M
	INNER JOIN RAW_D580V V ON V.PERSON_REF=M.PERSON_REF AND V.REF=M.POST_REF AND V.POST_END_DATE IS NULL
	WHERE M.POST_REF>0 AND ID IN (1000,0900,1077,1311) 
) R


WHERE RN=1


	SELECT DISTINCT EMPLOYEE_PERSON_REFERENCE,EMPLOYEE_POST_REFERENCE FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
	WHERE EMPLOYEE_POST_END_DATE>GETDATE() AND  EMPLOYEE_POST_CONTRACTED_HOURS>0
	AND EMPLOYEE_PERSON_REFERENCE=01031427


	SELECT * FROM  raw_D559M 
	WHERE POST_REF>0


	SELECT 
	---PERSON_REF,
	POST_REF---,P.CURRENT_GRADE,P.HR_FTE_HOURS
	,hr
	----,POINT_VALUE,POINT_RATE
	,COALESCE(CASE WHEN P.CURRENT_GRADE='CWZERO' THEN P.POINT_RATE ELSE NULL END 
	,[1000],[0900],[1077],[1311]) [sal/rate]

	FROM 
	(

		SELECT 
	DISTINCT R.PERSON_REF,
	R.POST_REF ,R.HR_FTE_HOURS
	,hr,R.CURRENT_GRADE,ID,R.AMOUNT,POINT_VALUE,POINT_RATE
	
	FROM 
	(
	SELECT M.PERSON_REF,M.POST_REF,V.CURRENT_GRADE,HR,HR.HR_FTE_HOURS,POINT_VALUE,POINT_RATE
	,
	 ROW_NUMBER() OVER (PARTITION BY M.PERSON_REF,M.POST_REF ORDER BY  EMP_PH_TAX_YEAR DESC, EMP_PH_TAX_PERIOD DESC)RN ,ID,M.AMOUNT
	
	FROM  raw_D559M  M
	INNER JOIN RAW_D580V V ON V.PERSON_REF=M.PERSON_REF AND V.REF=M.POST_REF AND V.POST_END_DATE IS NULL
	INNER JOIN raw_d591m HR ON HR.PERSON_REF=V.PERSON_REF AND HR.EMP_POST_REF=V.REF  AND hr.HR_END_DATE IS null
	LEFT JOIN raw_d554m  pr ON  pr.PERSON_REF=v.PERSON_REF  AND pr.POST_REF=v.REF AND pr.END_DATE IS null
	WHERE M.POST_REF>0 AND ID IN (1000,0900,1077,1311) 
	
) R


WHERE RN=1
) T

PIVOT (MAX(AMOUNT) FOR ID IN ([1000],[0900],[1077],[1311])) P

---01017794,01087744,01069256


SELECT  DISTINCT RIGHT(r.PERSON_REF,7),r.PERSON_REF,r.POST_REF,POINT_VALUE,POINT_RATE FROM raw_d554m r
INNER JOIN raw_d559m j ON r.PERSON_REF=j.PERSON_REF AND r.POST_REF=j.POST_REF
WHERE r.END_DATE IS null

SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
WHERE  EMPLOYEE_POST_END_DATE>GETDATE() AND EMPLOYEE_POST_CONTRACTED_HOURS>0

SELECT * FROM  dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
----01001871


SELECT * FROM dbo.RAW_D591M WHERE PERSON_REF=01081964





