





SELECT  y.D4 ,p.DEPARTMENT department,p.EMPLOYEE_ClEAN_JOB_TITLE job_title---,v.POST_NUMBER post_number
,p.EMPLOYEE_POST_REFERENCE post_ref, CASE WHEN p.PAYROLL_FREQUENCY LIKE '%Monthly %' THEN r.FULL_AMOUNT ELSE r.UNADJ_AMOUNT/p.EMPLOYEE_POST_CONTRACTED_HOURS end [salary] ,p.EMPLOYEE_PERSON_REFERENCE,p.EMPLOYEE_JOB_TYPE,p.PAYROLL_FREQUENCY



FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS p

LEFT JOIN (  select PERSON_REF,POST_REF,FULL_AMOUNT,UNADJ_AMOUNT FROM raw_D559M 
 WHERE  PERSON_REF=01082641
) r ON r.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE
    AND r.POST_REF=p.EMPLOYEE_POST_REFERENCE 
	
INNER JOIN 

(	
SELECT  p.D4 ,ep.PERSON_REF,ep.EMP_POST_REF   FROM raw_d455m ep INNER JOIN dbo.RL_PERS_HIERARCHY p
ON ep.PERS_STR_REF_LINK=p.CHILD_ID

WHERE ep.EMP_POST_END_DATE IS NULL 
) y ON y.PERSON_REF=p.EMPLOYEE_PERSON_REFERENCE AND y.EMP_POST_REF=p.EMPLOYEE_POST_REFERENCE

WHERE EMPLOYEE_POST_END_DATE>GETDATE()
AND p.EMPLOYEE_POST_CONTRACTED_HOURS>0

AND r.PERSON_REF IS null

AND v.POST_START_DATE BETWEEN '2022/07/01' AND GETDATE()

select * FROM raw_D559M 
 WHERE  PERSON_REF=01082641
SELECT DISTINCT PAYROLL_FREQUENCY FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS
WHERE EMPLOYEE_LAST_NAME LIKE '%nayakwa%'


SELECT * FROM dbo.SP_Portal_User_OrgHierarchy



-
-----
 select * FROM raw_D559M 
 WHERE PERSON_REF=01031186


 -----01007995
 ----313.50
 SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY_ALL_POSTS


 ---01013485


 ---01017739


-- SELECT 
--DISTINCT 
--	CASE	WHEN T1.COST_PAY_OR_DEDN_FLAG = 'D' THEN T1.COST_AMOUNT * - 1
--			ELSE T1.COST_AMOUNT
--			END AS AMOUNT
--	,T4.SORT_CODE
--	,T3.LONG_DESC
--	,T3.PAY_ELEMENT_ID
--	,T2.INITIALS
--	,T2.SURNAME
--	,T1.COST_TYPE_ALPHA
--	,T1.COST_TAX_YEAR_PER_SUPP_NO
--	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 1, 2)	    GL1 	
--	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 3, 4)	    GL2
--	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 7, 3)      GL3
--	,SUBSTRING(T1.LONG_COST_CENTRE_CODE, 10, 5)     GL4
--	,T1.COST_PE_ID_CODE
--	,T1.COST_PAY_TYPE 
--	,T1.COST_PAY_OR_DEDN_FLAG
--	,T1.COST_PAY_DATE
--	,T1.COST_LEVEL1_PAY_STR_ID
--	,T1.COST_AMOUNT 
--	,T1.EMPLOYEE_NUMBER 
--	,T1.LONG_COST_CENTRE_CODE 

--FROM RAW_D415M T1
--	INNER JOIN RAW_D500M T2 ON T1.PERSON_REF = T2.PERSON_REF
--	INNER JOIN RAW_D755M T3 ON T1.COST_PE_ID = T3.PAY_ELEMENT_ID
--	INNER JOIN RAW_D200M T5 ON T1.COST_POST_NUMBER = T5.NUMBER_R
--	LEFT JOIN  RAW_D300M T4 ON T5.JOB_REF = T4.REF
--WHERE   
--(T1.COSTING_RUN_NUMBER		= @RUN_NO )
--AND
--(T1.COST_LEVEL1_PAY_STR_ID	= @PAY_ST_ID )
--ORDER BY 
--	COST_PAY_DATE ASC
--	,GL2 ASC
--	,EMPLOYEE_NUMBER ASC
--	,GL3 ASC
--	,GL4 ASC



--	select * FROM RAW_D415M T1