SELECT * FROM dbo.RL_Meta
WHERE COLUMN_NAME LIKE '%vehicle%' 
---AND COLUMN_NAME LIKE '%next%'



SELECT m.DATA_VALUE, p.DICT_NAME,p.TEXT,n.EMPLOYEE_PERSON_REFERENCE,n.EMPLOYEE_POST_START_DATE  FROM dbo.RAW_D970M m

INNER JOIN raw_d892m p ON p.REF=m.FIELD_REF
INNER JOIN dbo.Raw_D455M u ON u.EMP_POST_REF=m.DATA_KEY_id AND u.EMP_POST_END_DATE IS NULL
INNER JOIN raw_D550m i ON i.PERSON_REF=u.PERSON_REF AND i.END_DATE IS NULL
INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY n ON n.EMPLOYEE_PERSON_REFERENCE=i.PERSON_REF

WHERE m.SCREEN_REF='US_CRB' AND n.EMPLOYEE_POST_END_DATE>GETDATE()



SELECT Min(pers_crb_cert_iss_date) FROM raw_D208M t
left JOIN  dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY p ON t.person_ref=p.EMPLOYEE_PERSON_REFERENCE
WHERE p.EMPLOYEE_POST_END_DATE >GETDATE()

SELECT *   FROM raw_D208M t
WHERE person_ref=01059666
---1329656805


SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY
WHERE EMPLOYEE_LAST_NAME LIKE '%nayakwad%'
SELECT * FROM raw_d591m