

IF OBJECT_ID('tempdb..#employee_manager_Hierar') IS NOT NULL DROP TABLE #employee_manager_Hierar
IF OBJECT_ID('tempdb..#eer')                     IS NOT NULL DROP TABLE #eer    
IF OBJECT_ID('tempdb..#Employee_Parents')        IS NOT NULL DROP TABLE #Employee_Parents


SELECT * INTO #employee_manager_Hierar FROM  employee_manager_ref  


;WITH cte
AS
(
SELECT person_ref,Manager_ref ,1 ord FROM #employee_manager_Hierar c 
UNION ALL
SELECT ce.person_ref,e.Manager_ref,e.ord+1 AS ord FROM #employee_manager_Hierar ce
INNER JOIN  cte e ON ce.Manager_Ref=e.person_ref
WHERE e.ord<10
)

SELECT  * INTO #eer   FROM cte  


SELECT person_ref,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]

INTO #Employee_Parents

FROM 
(

SELECT 
person_ref,
manager_ref 
,ord
FROM #eer r
---WHERE person_ref=01072174
) p
PIVOT (MAX(manager_ref) FOR  ord IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10])) pv



--SELECT * FROM #Employee_Parents

SELECT e.person_ref AS Employee_Person_Ref

,concat(ep.EMPLOYEE_FIRST_NAME,' ',ep.EMPLOYEE_LAST_NAME) Employee_Name
,CONCAT(ed_Level1.EMPLOYEE_FIRST_NAME,' ',ed_Level1.EMPLOYEE_LAST_NAME)  Level1_Employee,
concat(ed_Level2.EMPLOYEE_FIRST_NAME,' ',ed_Level2.EMPLOYEE_LAST_NAME)  Level2_Employee,
concat(ed_Level3.EMPLOYEE_FIRST_NAME,' ',ed_Level3.EMPLOYEE_LAST_NAME)  Level3_Employee
,concat(ed_Level4.EMPLOYEE_FIRST_NAME,' ',ed_Level4.EMPLOYEE_LAST_NAME)   Level4_Employee,
concat(ed_Level5.EMPLOYEE_FIRST_NAME,' ',ed_Level5.EMPLOYEE_LAST_NAME)    Level5_Employee,
concat(ed_Level6.EMPLOYEE_FIRST_NAME,' ',ed_Level6.EMPLOYEE_LAST_NAME)    Level6_Employee,
concat(ed_Level7.EMPLOYEE_FIRST_NAME,' ',ed_Level7.EMPLOYEE_LAST_NAME)    Level7_Employee,
concat(ed_Level8.EMPLOYEE_FIRST_NAME,' ',ed_Level8.EMPLOYEE_LAST_NAME)    Level8_Employee,
concat(ed_Level9.EMPLOYEE_FIRST_NAME,' ',ed_Level9.EMPLOYEE_LAST_NAME)    Level9_Employee,
concat(ed_Level10.EMPLOYEE_FIRST_NAME,' ',ed_Level10.EMPLOYEE_LAST_NAME)    Level10_Employee
,ep.EMPLOYEE_POST_NUMBER,ep.EMPLOYEE_CLEAN_JOB_TITLE,ep.EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level1.EMPLOYEE_POST_NUMBER  Level1_EMPLOYEE_POST_NUMBER,ed_Level1.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level1_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level1.EMPLOYEE_EMPLOYEE_NUMBER ed_Level1_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level2.EMPLOYEE_POST_NUMBER  Level2_EMPLOYEE_POST_NUMBER,ed_Level2.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level2_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level2.EMPLOYEE_EMPLOYEE_NUMBER ed_Level2_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level3.EMPLOYEE_POST_NUMBER  Level3_EMPLOYEE_POST_NUMBER,ed_Level3.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level3_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level3.EMPLOYEE_EMPLOYEE_NUMBER ed_Level3_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level4.EMPLOYEE_POST_NUMBER  Level4_EMPLOYEE_POST_NUMBER,ed_Level4.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level4_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level4.EMPLOYEE_EMPLOYEE_NUMBER ed_Level4_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level5.EMPLOYEE_POST_NUMBER  Level5_EMPLOYEE_POST_NUMBER,ed_Level5.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level5_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level5.EMPLOYEE_EMPLOYEE_NUMBER ed_Level5_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level6.EMPLOYEE_POST_NUMBER  Level6_EMPLOYEE_POST_NUMBER,ed_Level6.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level6_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level6.EMPLOYEE_EMPLOYEE_NUMBER ed_Level6_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level7.EMPLOYEE_POST_NUMBER  Level7_EMPLOYEE_POST_NUMBER,ed_Level7.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level7_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level7.EMPLOYEE_EMPLOYEE_NUMBER ed_Level7_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level8.EMPLOYEE_POST_NUMBER  Level8_EMPLOYEE_POST_NUMBER,ed_Level8.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level8_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level8.EMPLOYEE_EMPLOYEE_NUMBER ed_Level8_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level9.EMPLOYEE_POST_NUMBER  Level9_EMPLOYEE_POST_NUMBER,ed_Level9.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level9_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level9.EMPLOYEE_EMPLOYEE_NUMBER ed_Level9_EMPLOYEE_EMPLOYEE_NUMBER
,ed_Level10.EMPLOYEE_POST_NUMBER  Level10_EMPLOYEE_POST_NUMBER,ed_Level10.EMPLOYEE_CLEAN_JOB_TITLE  ed_Level10_EMPLOYEE_CLEAN_JOB_TITLE,ed_Level10.EMPLOYEE_EMPLOYEE_NUMBER ed_Level10_EMPLOYEE_EMPLOYEE_NUMBER

FROM #Employee_Parents e
INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ep ON e.person_ref=ep.EMPLOYEE_PERSON_REFERENCE AND ep.EMPLOYEE_POST_END_DATE>GETDATE()
INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level1 ON e.[1]=ed_Level1.EMPLOYEE_PERSON_REFERENCE AND ed_Level1.EMPLOYEE_POST_END_DATE>GETDATE()
INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level2 ON e.[2]=ed_Level2.EMPLOYEE_PERSON_REFERENCE AND ed_Level2.EMPLOYEE_POST_END_DATE>GETDATE()
INNER JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level3 ON e.[3]=ed_Level3.EMPLOYEE_PERSON_REFERENCE AND ed_Level3.EMPLOYEE_POST_END_DATE>GETDATE()
left JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level4 ON e.[4]=ed_Level4.EMPLOYEE_PERSON_REFERENCE  AND ed_Level4.EMPLOYEE_POST_END_DATE>GETDATE()
left JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level5 ON e.[5]=ed_Level5.EMPLOYEE_PERSON_REFERENCE   AND ed_Level5.EMPLOYEE_POST_END_DATE>GETDATE()
left JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level6 ON e.[6]=ed_Level6.EMPLOYEE_PERSON_REFERENCE  AND ed_Level6.EMPLOYEE_POST_END_DATE>GETDATE()
left JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level7 ON e.[7]=ed_Level7.EMPLOYEE_PERSON_REFERENCE    AND ed_Level7.EMPLOYEE_POST_END_DATE>GETDATE()
left JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level8 ON e.[8]=ed_Level8.EMPLOYEE_PERSON_REFERENCE    AND ed_Level8.EMPLOYEE_POST_END_DATE>GETDATE()
left JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level9 ON e.[9]=ed_Level9.EMPLOYEE_PERSON_REFERENCE    AND ed_Level9.EMPLOYEE_POST_END_DATE>GETDATE()
left JOIN dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY ed_Level10 ON e.[10]=ed_Level10.EMPLOYEE_PERSON_REFERENCE  AND ed_Level10.EMPLOYEE_POST_END_DATE>GETDATE()







SELECT * FROM dbo.REC_RESOURCELINK_ACTIVE_DIRECTORY
WHERE EMPLOYEE_EMPLOYEE_NUMBER='010377'
AND EMPLOYEE_POST_END_DATE>GETDATE()